Sy5
triniti/apollo-php pull request #6
Opened 2020-10-01 18:13 UTC by efjacobson

- with the shift from `stream_id` to `node_ref` in the history request handlers, which will be resolved by a proxy in core, not sure how to make a `GetPollHistoryRequestHandlerTest`

2020-10-02 20:14 UTC, gdbrown requested changes

2020-10-02 20:14 UTC, gdbrown commented on composer.json
> +    },
@efjacobson this shouldn't be needed, the "dev-blah" is handled by composer automatically.

2020-10-02 20:14 UTC, gdbrown commented on src/CastVoteHandler.php
> +            CastVoteV1::schema()->getCurie(),
@efjacobson just use strings now

2020-10-02 20:14 UTC, gdbrown commented on src/CreatePollHandler.php
@efjacobson class not needed, delete it

2020-10-02 20:14 UTC, gdbrown commented on src/DeletePollHandler.php
@efjacobson delete this class

2020-10-02 20:14 UTC, gdbrown commented on src/DeletePollHandler.php
@efjacobson delete this class

2020-10-02 20:14 UTC, gdbrown commented on src/ExpirePollHandler.php
@efjacobson delete this

2020-10-02 20:14 UTC, gdbrown commented on src/GetPollHistoryRequestHandler.php
> +class GetPollHistoryRequestHandler extends GetNodeHistoryRequestHandler
@efjacobson delete this class, one will go at site level core for all legacy requests

2020-10-02 20:14 UTC, gdbrown commented on src/GetPollRequestHandler.php
>      {
@efjacobson class not needed, delete this, done one in site core for legacy requests

2020-10-02 20:14 UTC, gdbrown commented on src/MarkPollAsDraftHandler.php
@efjacobson delete class

2020-10-02 20:14 UTC, gdbrown commented on src/MarkPollAsPendingHandler.php
> +class MarkPollAsPendingHandler extends MarkNodeAsPendingHandler
@efjacobson delete class

2020-10-02 20:14 UTC, gdbrown commented on src/NcrPollProjector.php
@efjacobson delete class

2020-10-02 20:14 UTC, gdbrown commented on src/NcrPollStatsProjector.php
>          $this->ncr = $ncr;
@efjacobson we'll discuss this one, needs moar

2020-10-02 20:14 UTC, gdbrown commented on src/PbjxHelperTrait.php
>      {
@efjacobson delete trait

2020-10-02 20:14 UTC, gdbrown commented on src/PollStatsAggregate.php
> +     *
@efjacobson probably won't been needed, delete for now

2020-10-02 20:14 UTC, gdbrown commented on src/PublishPollHandler.php
>      public static function handlesCuries(): array
@efjacobson delete class

2020-10-02 20:14 UTC, gdbrown commented on src/SearchPollsRequestHandler.php
> +            SearchPollsRequestV1::schema()->getCurie(),
@efjacobson use string with new and old, e.g. https://github.com/gdbots/iam-php/blob/master/src/SearchUsersRequestHandler.php#L21

2020-10-02 20:14 UTC, gdbrown commented on src/UnpublishPollHandler.php
>      {
@efjacobson delete it

2020-10-02 20:14 UTC, gdbrown commented on src/UpdatePollHandler.php
>      public static function handlesCuries(): array
@efjacobson canceled

2020-10-02 21:59 UTC, efjacobson commented on src/NcrPollProjector.php
@gdbrown i need it for the PollAggregateTest https://github.com/triniti/apollo-php/blob/sy5/tests/PollAggregateTest.php#L40, unless you want to not do that or do it a different way

2020-10-02 22:04 UTC, gdbrown commented on src/NcrPollProjector.php
@efjacobson use the projector from gdbots/ncr

2020-10-02 22:13 UTC, efjacobson commented
@gdbrown think i got everything, can discuss NcrPollStatsProjector whenever

2020-10-05 22:14 UTC, efjacobson commented
@gdbrown lmk know what you think of NcrPollStatsProjector now. fwiw although everything has been consolidated into the single method onPollProjected, i think it is less readable. maybe a good middle ground would be to handle all the similar status events there, with dedicated methods for created, deleted, and vote-casted

2020-10-05 22:49 UTC, gdbrown commented
@efjacobson i don't think we need to do any conditional logic for the different events causing the projection.  just take the poll node as it is and apply that.  only oddball is if the item is deleted then delete the stats.  the rest is straight copy of current poll to poll stats.

2020-10-06 00:32 UTC, efjacobson commented
@gdbrown like so? https://github.com/triniti/apollo-php/blob/f3802a58c19272474738d0a4e9cf4055c531b315/src/NcrPollStatsProjector.php#L38

will `triniti:apollo:mixin:poll.projected` pick up on the vote-casted projection?

2020-10-06 00:38 UTC, gdbrown commented
@efjacobson 
- don't worry about the mixin checking... just check the node status... the event has the node.  `$event->getNode()` is the poll and you can safely use that instead of fetching again later in this method.
- vote casted should remain as its own method and subscribe to that event.

lmk if that makes sense.

2020-10-06 01:05 UTC, efjacobson commented
@gdbrown this going in the right direction? https://github.com/triniti/apollo-php/pull/6/commits/be57b207e74c7b0cbc721effa97f7bda170a82ca

2020-10-06 01:19 UTC, gdbrown commented
@efjacobson now we're cooking with grease.

2021-02-06 02:32 UTC, gdbrown approved these changes

2021-02-06 02:32 UTC, merged